FROM fluent/fluentd:v1.16-debian-1

USER root

RUN apt-get update
RUN apt-get install -y build-essential wget
RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates


RUN fluent-gem install fluent-plugin-rewrite-tag-filter
RUN fluent-gem install fluent-plugin-multi-format-parser
RUN fluent-gem install fluent-plugin-elasticsearch
RUN fluent-gem install fluent-plugin-kafka --no-document
RUN fluent-gem install rdkafka --no-document


USER fluent
