spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER}
    consumer-group: ${KAFKA_GROUP_ID}
  elasticsearch:
    rest:
      uris: ${ELASTICSEARCH_REST_URIS}
    client.reactive:
      endpoints: ${ELASTICSEARCH_CLIENT_ENDPOINT}
      username: ${ELASTICSEARCH_CLIENT_USERNAME}
      password: ${ELASTICSEARCH_CLIENT_PASSWORD}
      use-ssl: false

kafka:
  topics:
    log_events_topic: ${KAFKA_LOG_EVENTS_TOPIC}
    group_id: ${KAFKA_GROUP_ID}

logging:
  level:
    root: INFO
    mx.com.interware: INFO
