server:
  port: 8080
  servlet:
    context-path: /app
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - health
        - info
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    mx.com.interware: ${LOG_LEVEL_MS:DEBUG}
spring:
  application:
    name: POC Monitoreo logs Invex
  banner:
    location: banner.txt
  profiles:
    active: release
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api
#  api-docs:
#    path: /api-docs